name: e2e Test

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
#    schedule:
#      - cron: '*/30 * * * *'

jobs:
  e2e-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: ''
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Spinup app
        run: RUNNER_TRACKING_ID="" && npx http-server -p 3000 --cors &
      - name: test app is still running
        run: curl -i localhost:3000
      - name: Verify
        uses: cypress-io/github-action@v6
#        with:
#          record: true
#        env:
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

